# Student Services MCP Demo Notebook

Author: Eidan J. Rosado

This notebook is meant as an example to end-users on how to leverage the StudentServicesMCPClient from the repo and use the exposed tools. For details on how to use this with Cursor, see README.md.

### Import Dependencies and Constants

In [58]:
# First cell - Import the MCP session
import os
import json
import pandas as pd
from src.client import StudentServicesMCPClient
from src.utils.generate_test_jwt import generate_jwt
from src.config.settings import settings

# Choose between your hugging face space or local server
BASE_URL = f"http://{settings.server.HOST}:7862/mcp"
HF_SPACE_URL = f"{settings.hf.HUGGINGFACE_SPACE_URL}/mcp"

## Preview Data

In [59]:
finaid_df = pd.read_csv("dist/data/synthetic_financial_aid_determinations.csv")

finaid_df.head()

,id,name,gpa,field_of_study,financial_aid,requirements
0,S97E19,Dr. Renee Burgess,2.37,Anthropology,['Behavioral and Social Sciences Grant'],['Field of Study in Behavioral and Social Scie...
1,S7CFE9,Sean Collins,3.84,Music,"['Presidential Scholarship', 'Liberal Arts Fel...","['GPA ≥ 3.8', 'Field of Study in Liberal Arts']"
2,SE0FC0,William Atkins,3.14,Biology,['STEM Excellence Award'],['Field of Study in STEM']
3,S44E47,Tara Mcbride,3.89,Philosophy,"['Presidential Scholarship', 'Liberal Arts Fel...","['GPA ≥ 3.8', 'Field of Study in Liberal Arts']"
4,S8107B,Kevin Munoz,3.66,Mathematics,"[""Dean's Merit Scholarship"", 'STEM Excellence ...","['GPA ≥ 3.6', 'Field of Study in STEM', 'GPA ≥..."

In [60]:
student_records_df = pd.read_csv("dist/data/synthetic_population_data.csv")

student_records_df.head()

,student_id,name,email,phone,address,enrollment_status,major,year,gpa,work_hours,goal,past_terms,notes,financial_status
0,S97E19,Dr. Renee Burgess,s97e19@university.edu,555-244-3320,"508 University Ave, College Town, CT 98754",Full-time,Anthropology,Senior,2.37,0,complete degree in 4 years,"[{""term"": ""Summer 2024"", ""credits"": 16, ""stres...",[],"{'efc': 10299, 'dependency_status': 'Dependent..."
1,S7CFE9,Sean Collins,s7cfe9@university.edu,555-827-7363,"884 University Ave, College Town, CT 67624",Full-time,Music,Freshman,3.84,20,graduate in 4 years,"[{""term"": ""Fall 2024"", ""credits"": 25, ""stress""...",[],"{'efc': 16327, 'dependency_status': 'Dependent..."
2,SE0FC0,William Atkins,se0fc0@university.edu,555-248-7220,"789 University Ave, College Town, CT 45988",Full-time,Biology,Junior,3.14,30,graduate in 2 years,"[{""term"": ""Spring 2024"", ""credits"": 10, ""stres...",[],"{'efc': 14460, 'dependency_status': 'Dependent..."
3,S44E47,Tara Mcbride,s44e47@university.edu,555-746-6536,"511 University Ave, College Town, CT 51947",Full-time,Philosophy,Senior,3.89,25,complete degree in 4 years,"[{""term"": ""Spring 2024"", ""credits"": 27, ""stres...",[],"{'efc': 3547, 'dependency_status': 'Independen..."
4,S8107B,Kevin Munoz,s8107b@university.edu,555-359-4309,"183 University Ave, College Town, CT 59432",Full-time,Mathematics,Junior,3.66,25,graduate in 3 years,"[{""term"": ""Spring 2024"", ""credits"": 24, ""stres...",[],"{'efc': 1187, 'dependency_status': 'Independen..."

In [61]:
# preview single term data structure for a student
student_records_df[student_records_df["student_id"] == "S8107B"]

,student_id,name,email,phone,address,enrollment_status,major,year,gpa,work_hours,goal,past_terms,notes,financial_status
4,S8107B,Kevin Munoz,s8107b@university.edu,555-359-4309,"183 University Ave, College Town, CT 59432",Full-time,Mathematics,Junior,3.66,25,graduate in 3 years,"[{""term"": ""Spring 2024"", ""credits"": 24, ""stres...",[],"{'efc': 1187, 'dependency_status': 'Independen..."

### Connect to Server

In [ ]:
# Setup the client
client = StudentServicesMCPClient(
    base_url=BASE_URL,
    auth_token=None,
)
await client.connect_to_server()

Connecting to server at: http://0.0.0.0:7862/mcp

Connected to server with tools: ['root__get', 'fetch_student_profile', 'fetch_student_profile_by_name', 'fetch_students', 'fetch_academic_history', 'fetch_financial_aid_eligibility', 'submit_note', 'fetch_course_plan', 'submit_course_plan']

Error in sse_reader: peer closed connection without sending complete message body (incomplete chunked read)

### Fetch Top n Students

In [63]:
# Fetch students
limit = 10
students_result = await client.fetch_students(limit=limit)

students = json.loads(students_result[0].text)
students_df = pd.DataFrame(students)
students_df

,student_id,name,email,phone,address,enrollment_status,major,year,gpa,work_hours,goal,past_terms,notes,financial_status,is_need_based_qualified
0,S97E19,Dr. Renee Burgess,s97e19@university.edu,555-244-3320,"508 University Ave, College Town, CT 98754",Full-time,Anthropology,Senior,2.37,0,complete degree in 4 years,"[{'term': 'Summer 2024', 'credits': 16, 'stres...",[],"{'efc': 10299, 'dependency_status': 'Dependent...",True
1,S7CFE9,Sean Collins,s7cfe9@university.edu,555-827-7363,"884 University Ave, College Town, CT 67624",Full-time,Music,Freshman,3.84,20,graduate in 4 years,"[{'term': 'Fall 2024', 'credits': 25, 'stress'...",[],"{'efc': 16327, 'dependency_status': 'Dependent...",True
2,SE0FC0,William Atkins,se0fc0@university.edu,555-248-7220,"789 University Ave, College Town, CT 45988",Full-time,Biology,Junior,3.14,30,graduate in 2 years,"[{'term': 'Spring 2024', 'credits': 10, 'stres...",[],"{'efc': 14460, 'dependency_status': 'Dependent...",True
3,S44E47,Tara Mcbride,s44e47@university.edu,555-746-6536,"511 University Ave, College Town, CT 51947",Full-time,Philosophy,Senior,3.89,25,complete degree in 4 years,"[{'term': 'Spring 2024', 'credits': 27, 'stres...",[],"{'efc': 3547, 'dependency_status': 'Independen...",False
4,S8107B,Kevin Munoz,s8107b@university.edu,555-359-4309,"183 University Ave, College Town, CT 59432",Full-time,Mathematics,Junior,3.66,25,graduate in 3 years,"[{'term': 'Spring 2024', 'credits': 24, 'stres...",[],"{'efc': 1187, 'dependency_status': 'Independen...",True
5,S98EA8,Brandon Sanchez,s98ea8@university.edu,555-628-2983,"445 University Ave, College Town, CT 35029",Full-time,Education,Sophomore,3.51,40,graduate in 2 years,"[{'term': 'Summer 2024', 'credits': 18, 'stres...",[],"{'efc': 2092, 'dependency_status': 'Independen...",True
6,S936D6,Harold Monroe,s936d6@university.edu,555-142-7594,"134 University Ave, College Town, CT 39458",Full-time,Biology,Freshman,2.41,30,complete degree in 3 years,"[{'term': 'Summer 2024', 'credits': 14, 'stres...",[],"{'efc': 751, 'dependency_status': 'Independent...",False
7,S18C25,John Lewis,s18c25@university.edu,555-859-4433,"162 University Ave, College Town, CT 17134",Full-time,History,Freshman,2.65,0,finish program within 4 years,"[{'term': 'Spring 2025', 'credits': 24, 'stres...",[],"{'efc': 16815, 'dependency_status': 'Dependent...",True
8,S0D830,Leonard James,s0d830@university.edu,555-987-3841,"313 University Ave, College Town, CT 47990",Full-time,Anthropology,Sophomore,2.46,25,finish program within 2 years,"[{'term': 'Spring 2025', 'credits': 20, 'stres...",[],"{'efc': 4073, 'dependency_status': 'Independen...",True
9,S2079F,Susan Woods,s2079f@university.edu,555-692-2470,"224 University Ave, College Town, CT 25191",Full-time,Anthropology,Freshman,3.56,30,graduate in 5 years,"[{'term': 'Fall 2023', 'credits': 10, 'stress'...",[],"{'efc': 6086, 'dependency_status': 'Dependent'...",False

In [64]:
lookup = await client.fetch_student_profile_by_name("Alice Jones")
json.loads(lookup[0].text)

{'student_id': 'S3879B',
 'name': 'Alice Jones',
 'email': 's3879b@university.edu',
 'phone': '555-760-9656',
 'address': '569 University Ave, College Town, CT 25604',
 'enrollment_status': 'Full-time',
 'major': 'History',
 'year': 'Senior',
 'gpa': 3.88,
 'work_hours': 35,
 'goal': 'complete degree in 5 years',
 'past_terms': [{'term': 'Fall 2024',
   'credits': 24,
   'stress': 'moderate',
   'courses': [{'course_code': 'HIST108',
     'title': 'World History',
     'credits': 3,
     'grade': 'A-'},
    {'course_code': 'HIST113',
     'title': 'American History',
     'credits': 3,
     'grade': 'A-'},
    {'course_code': 'HIST122',
     'title': 'European History',
     'credits': 3,
     'grade': 'A'},
    {'course_code': 'HIST136',
     'title': 'Ancient History',
     'credits': 4,
     'grade': 'A-'},
    {'course_code': 'HIST145',
     'title': 'Modern History',
     'credits': 3,
     'grade': 'B+'},
    {'course_code': 'HIST159',
     'title': 'Historical Research',
     'credits': 4,
     'grade': 'A-'},
    {'course_code': 'HIST163',
     'title': 'Historiography',
     'credits': 4,
     'grade': 'B+'}]}],
 'notes': [],
 'financial_status': {'efc': 9766,
  'dependency_status': 'Independent',
  'household_income': 96158,
  'household_size': 4},
 'is_need_based_qualified': False}

### Fetch Financial Aid Eligibility for Students

In [65]:
students[0]

{'student_id': 'S97E19',
 'name': 'Dr. Renee Burgess',
 'email': 's97e19@university.edu',
 'phone': '555-244-3320',
 'address': '508 University Ave, College Town, CT 98754',
 'enrollment_status': 'Full-time',
 'major': 'Anthropology',
 'year': 'Senior',
 'gpa': 2.37,
 'work_hours': 0,
 'goal': 'complete degree in 4 years',
 'past_terms': [{'term': 'Summer 2024',
   'credits': 16,
   'stress': 'high',
   'courses': [{'course_code': 'ANTH107',
     'title': 'Introduction to Field',
     'credits': 3,
     'grade': 'C+'},
    {'course_code': 'ANTH117',
     'title': 'Advanced Topics',
     'credits': 3,
     'grade': 'C-'},
    {'course_code': 'ANTH124',
     'title': 'Research Methods',
     'credits': 4,
     'grade': 'C-'},
    {'course_code': 'ANTH137',
     'title': 'Seminar',
     'credits': 3,
     'grade': 'C+'},
    {'course_code': 'ANTH148',
     'title': 'Practicum',
     'credits': 3,
     'grade': 'C+'}]},
  {'term': 'Fall 2023',
   'credits': 21,
   'stress': 'low',
   'courses': [{'course_code': 'ANTH206',
     'title': 'Introduction to Field',
     'credits': 3,
     'grade': 'B-'},
    {'course_code': 'ANTH217',
     'title': 'Advanced Topics',
     'credits': 3,
     'grade': 'C+'},
    {'course_code': 'ANTH225',
     'title': 'Research Methods',
     'credits': 3,
     'grade': 'C'},
    {'course_code': 'ANTH237',
     'title': 'Seminar',
     'credits': 3,
     'grade': 'C+'},
    {'course_code': 'ANTH248',
     'title': 'Practicum',
     'credits': 3,
     'grade': 'C-'},
    {'course_code': 'ANTH253',
     'title': 'Capstone Project',
     'credits': 3,
     'grade': 'C'},
    {'course_code': 'ANTH268',
     'title': 'Advanced Introduction to Field',
     'credits': 3,
     'grade': 'C+'}]}],
 'notes': [],
 'financial_status': {'efc': 10299,
  'dependency_status': 'Dependent',
  'household_income': 44554,
  'household_size': 5},
 'is_need_based_qualified': True}

In [66]:
# Check eligibility for Allison Hill
eligibility = await client.fetch_financial_aid_eligibility(students[0]["student_id"])
print(eligibility[0].text)

"Student Dr. Renee Burgess (ID: S97E19) has a GPA of 2.37 in Anthropology. They are eligible for the ['Behavioral and Social Sciences Grant']. Requirements: ['Field of Study in Behavioral and Social Sciences']"

In [67]:
students[4]

{'student_id': 'S8107B',
 'name': 'Kevin Munoz',
 'email': 's8107b@university.edu',
 'phone': '555-359-4309',
 'address': '183 University Ave, College Town, CT 59432',
 'enrollment_status': 'Full-time',
 'major': 'Mathematics',
 'year': 'Junior',
 'gpa': 3.66,
 'work_hours': 25,
 'goal': 'graduate in 3 years',
 'past_terms': [{'term': 'Spring 2024',
   'credits': 24,
   'stress': 'moderate',
   'courses': [{'course_code': 'MATH105',
     'title': 'Calculus I',
     'credits': 3,
     'grade': 'A-'},
    {'course_code': 'MATH115',
     'title': 'Calculus II',
     'credits': 3,
     'grade': 'B+'},
    {'course_code': 'MATH128',
     'title': 'Calculus III',
     'credits': 4,
     'grade': 'A'},
    {'course_code': 'MATH133',
     'title': 'Linear Algebra',
     'credits': 4,
     'grade': 'A-'},
    {'course_code': 'MATH149',
     'title': 'Differential Equations',
     'credits': 3,
     'grade': 'A-'},
    {'course_code': 'MATH159',
     'title': 'Statistics',
     'credits': 4,
     'grade': 'A'},
    {'course_code': 'MATH169',
     'title': 'Abstract Algebra',
     'credits': 3,
     'grade': 'B'}]},
  {'term': 'Fall 2023',
   'credits': 15,
   'stress': 'moderate',
   'courses': [{'course_code': 'MATH207',
     'title': 'Calculus I',
     'credits': 3,
     'grade': 'B+'},
    {'course_code': 'MATH212',
     'title': 'Calculus II',
     'credits': 4,
     'grade': 'B+'},
    {'course_code': 'MATH226',
     'title': 'Calculus III',
     'credits': 4,
     'grade': 'A'},
    {'course_code': 'MATH239',
     'title': 'Linear Algebra',
     'credits': 4,
     'grade': 'B'}]}],
 'notes': [],
 'financial_status': {'efc': 1187,
  'dependency_status': 'Independent',
  'household_income': 90127,
  'household_size': 3},
 'is_need_based_qualified': True}

In [69]:
# Check eligibility for Student 4
eligibility = await client.fetch_financial_aid_eligibility(students[4]["student_id"])
print(eligibility[0].text)

"Student Kevin Munoz (ID: S8107B) has a GPA of 3.66 in Mathematics. They are eligible for the ['STEM Excellence Award']. Requirements: ['GPA \u2265 3.6', 'Field of Study in STEM']"